# niskan516's zsh config

has() {
  command -v "$1" 1>/dev/null 2>&1
}

zi_home="${HOME}/.zi"

if [ ! -f "${zi_home}/bin/zi.zsh" ]; then
  source <(curl -sL https://git.io/zi-loader)
  zzinit
fi

source "${zi_home}/bin/zi.zsh"

zi load mroth/evalcache
zi load z-shell/H-S-MW
zi light z-shell/F-Sy-H
zi light zsh-users/zsh-autosuggestions
zi ice blockf
zi light zsh-users/zsh-completions
zi snippet OMZL::clipboard.zsh
zi snippet OMZL::termsupport.zsh
zi snippet OMZP::git
zi snippet OMZP::dotenv
zi snippet OMZP::rbenv
zi snippet OMZP::sudo
zi load agkozak/zsh-z
zi load djui/alias-tips
zi load ael-code/zsh-colored-man-pages
zi load chrissicool/zsh-256color

export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH=${HOME}/.local/bin:$PATH
# fnm
export PATH=${HOME}/.local/share/fnm:$PATH

if ! has "rustc"; then
  echo "rust is not installed."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  source "$HOME/.cargo/env"
fi

if has starship; then
  _evalcache starship init zsh
else
  curl -sS https://starship.rs/install.sh | sh
  _evalcache starship init zsh
fi

if ! has "nvim"; then
  echo "nvim is not installed."
  sudo pacman -S neovim
fi

# if not installed, install lunarvim
if ! has "lvim"; then
  LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)
fi


# The meaning of these options can be found in man page of `zshoptions`.
setopt HIST_IGNORE_ALL_DUPS    # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS       # do not save duplicated command
setopt HIST_REDUCE_BLANKS      # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME # append command to history file immediately after execution
setopt EXTENDED_HISTORY        # record command start time

# show all the history stored.
alias history="fc -l 1"
alias ssh="ssh -v"
alias vi='lvim'
alias vim='lvim'
alias ws='webstorm'

# the detailed meaning of the below three variable can be found in `man zshparam`.
export HISTFILE=~/.histfile
export HISTSIZE=10000 # the number of items for the internal history list
export SAVEHIST=10000 # maximum number of items for the history file



# cache eval fnm
if has fnm; then
  _evalcache fnm env --use-on-cd
else
  curl -fsSL https://fnm.vercel.app/install | bash
  _evalcache fnm env --use-on-cd
fi


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/niskan516/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/niskan516/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/niskan516/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/niskan516/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

