# niskan516's zsh config

has() {
  command -v "$1" 1>/dev/null 2>&1
}

zi_home="${HOME}/.zi"

if [ ! -f "${zi_home}/bin/zi.zsh" ]; then
  source <(curl -sL https://git.io/zi-loader)
  zzinit
fi

source "${zi_home}/bin/zi.zsh"

zi load mroth/evalcache
zi load z-shell/H-S-MW
zi light z-shell/F-Sy-H
zi light zsh-users/zsh-autosuggestions
zi ice blockf
zi light zsh-users/zsh-completions
zi snippet OMZL::clipboard.zsh
zi snippet OMZL::termsupport.zsh
zi snippet OMZP::git
zi snippet OMZP::dotenv
zi snippet OMZP::rbenv
zi snippet OMZP::sudo
zi load agkozak/zsh-z
zi load djui/alias-tips
zi load ael-code/zsh-colored-man-pages
zi load chrissicool/zsh-256color

if has starship; then
  _evalcache starship init zsh
else
  curl -sS https://starship.rs/install.sh | sh
fi

if has rbenv; then
  _evalcache rbenv init - zsh
fi

# cache eval fnm
if has fnm; then
  _evalcache fnm env --use-on-cd
fi

if has /opt/homebrew/bin/brew; then
  _evalcache /opt/homebrew/bin/brew shellenv
fi

# the detailed meaning of the below three variable can be found in `man zshparam`.
export HISTFILE=~/.histfile
export HISTSIZE=10000 # the number of items for the internal history list
export SAVEHIST=10000 # maximum number of items for the history file

# The meaning of these options can be found in man page of `zshoptions`.
setopt HIST_IGNORE_ALL_DUPS    # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS       # do not save duplicated command
setopt HIST_REDUCE_BLANKS      # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME # append command to history file immediately after execution
setopt EXTENDED_HISTORY        # record command start time

# show all the history stored.
alias history="fc -l 1"

alias la="colorls -la"
alias ls='colorls'
alias lt="colorls --tree=1 -l"
alias lcs='colorls -lA --sd'
alias ssh="ssh -v"
alias vi='lvim'
alias vim='lvim'
alias python="python3"
alias ws='webstorm'
